object Version {
    const val APP_COMPAT = "1.2.0"
    const val CORE_TESTING = "2.1.0"
    const val CONSTRAINT = "2.0.4"
    const val CORE_KTX = "1.3.2"
    const val FRAGMENT_TESTING = "1.3.3"
    const val LIFECYCLE = "2.3.1"
    const val NAVIGATION = "2.3.5"
    const val TEST_RULES = "1.3.0"
    const val ESPRESSO = "3.3.0"
    const val JUNIT = "1.1.2"
    const val KAKAO = "2.4.0"
    const val GSON = "2.8.6"
    const val DAGGER = "2.35.1"
    const val LEAK_CANARY = "2.7"
    const val OK_HTTP = "4.9.1"
    const val RETROFIT = "2.9.0"
    const val MOCKK = "1.11.0"
    const val RX_ANDROID = "2.1.1"
    const val RX_JAVA = "2.2.21"
    const val DEPENDENCY_UPDATE_DETECTION = "1.3.1"
    const val COROUTINES = "1.5.0-RC"
    const val TURBINE = "0.4.1"
    const val GROUPIE = "2.9.0"
    const val RETROFIT_RX_ADAPTER = "1.0.0"
    const val RX_KOTLIN = "2.4.0"
    const val ROOM = "2.3.0"
    const val JUPITER = "5.7.1"

}
